theme: jekyll-theme-minimal
# basic options
title: The Distracted Learner
author: Dorene Smith
email: thedistractedlearner@gmail.com
description: A place to learn
twitter_username: thedistracted1
github_username:  thedistractedlearner

# Build settings
markdown: kramdown
theme: minima
